clear
clc

cst = actxserver('CSTStudio.Application');
mws = cst.invoke('NewMWS');

solver = invoke(mws, 'Solver');
solver.invoke('FrequencyRange', 27.9, 28.1);

mws.invoke('AddToHistory', 'set the frequency range',[...
sprintf( 'Solver.FrequencyRange "27.9", "28.1"')]);

mws.invoke('ChangeSolverType', 'HF IntegralEq');

mws.invoke('AddToHistory','Change Solver',[...
sprintf( 'ChangeSolverType "HF IntegralEq" ')]);



mws.invoke('SaveAs',['C:\Users\NooR\Desktop\Reflect_Array_Test_Folder\Reflector',num2str(round(rand()*1000)),'.cst'],'false');
dim_val = xlsread('dim_value');


warning('off','all');




%--------------------- Units History ---------------------
mws.invoke('AddToHistory', 'set the units',[...
sprintf( 'With Units\n') ...
sprintf('    .Geometry "mm"\n') ...
sprintf('    .Frequency "GHz"\n') ...
sprintf('    .Voltage "V"\n') ...
sprintf('    .Resistance "Ohm"\n') ...
sprintf('    .Inductance "NanoH"\n') ...
sprintf('    .TemperatureUnit  "Kelvin"\n') ...
sprintf('    .Time "ns"\n') ...
sprintf('    .Current "A"\n') ...
sprintf('    .Conductance "Siemens"\n') ...
sprintf('    .Capacitance "PikoF"\n') ...
sprintf('End With')]);
%---------------------------------------------------------



%------------------ Background History -------------------
mws.invoke('AddToHistory', 'Plot.DrawBox True',[...
sprintf('With Background\n') ...
sprintf('     .Type "Normal"\n') ...
sprintf('     .Epsilon "1.0"\n') ...
sprintf('     .Mue "1.0"\n') ...
sprintf('     .XminSpace "0.0"\n') ...
sprintf('     .XmaxSpace "0.0"\n') ...
sprintf('     .YminSpace "0.0"\n') ...
sprintf('     .YmaxSpace "0.0"\n') ...
sprintf('     .ZminSpace "0.0"\n') ...
sprintf('     .ZmaxSpace "0.0"\n') ...
sprintf('End With')]);
%---------------------------------------------------------


%------------------- Boundary History --------------------
mws.invoke('AddToHistory','Boundaries',[...
sprintf('With Boundary\n') ...
sprintf('     .Xmin "expanded open"\n') ...
sprintf('     .Xmax "expanded open"\n') ...
sprintf('     .Ymin "expanded open"\n') ...
sprintf('     .Ymax "expanded open"\n') ...
sprintf('     .Zmin "expanded open"\n') ...
sprintf('     .Zmax "expanded open"\n') ...
sprintf('     .Xsymmetry "none"\n') ...
sprintf('     .Ysymmetry "none"\n') ...
sprintf('     .Zsymmetry "none"\n') ...
sprintf('End With')]);
%---------------------------------------------------------


%------------------- Monitor History ---------------------

mws.invoke('AddToHistory','Define Farfield Monitors',[...
sprintf('With Monitor\n') ...
sprintf('    .Reset\n') ...
sprintf('    .Name "farfield 28 GHz"\n') ...
sprintf('    .Domain "Frequency"\n') ...
sprintf('    .FieldType "Farfield"\n') ...
sprintf('    .Frequency 28\n') ...
sprintf('    .ExportFarfieldSource "False"\n') ...
sprintf('    .Create\n') ...
sprintf('End With')]);
%---------------------------------------------------------


%---------------- Copper (annealed) History --------------
mws.invoke('AddToHistory','Define Copper Material',[...
sprintf('With Material\n') ...
sprintf('     .Reset\n') ...
sprintf('     .Name "Copper (annealed)"\n') ...
sprintf('     .Folder ""\n') ...
sprintf('.FrqType "static" \n') ...
sprintf('.Type "Normal" \n') ...
sprintf('.SetMaterialUnit "Hz", "mm" \n') ...
sprintf('.Epsilon "1" \n') ...
sprintf('.Mue "1.0" \n') ...
sprintf('.Kappa "5.8e+007" \n') ...
sprintf('.TanD "0.0" \n') ...
sprintf('.TanDFreq "0.0" \n') ...
sprintf('.TanDGiven "False" \n') ...
sprintf('.TanDModel "ConstTanD" \n') ...
sprintf('.KappaM "0" \n') ...
sprintf('.TanDM "0.0" \n') ...
sprintf('.TanDMFreq "0.0" \n') ...
sprintf('.TanDMGiven "False" \n') ...
sprintf('.TanDMModel "ConstTanD" \n') ...
sprintf('.DispModelEps "None" \n') ...
sprintf('.DispModelMue "None" \n') ...
sprintf('.DispersiveFittingSchemeEps "Nth Order" \n') ...
sprintf('.DispersiveFittingSchemeMue "Nth Order" \n') ...
sprintf('.UseGeneralDispersionEps "False" \n') ...
sprintf('.UseGeneralDispersionMue "False" \n') ...
sprintf('.FrqType "all" \n') ...
sprintf('.Type "Lossy metal" \n') ...
sprintf('.SetMaterialUnit "GHz", "mm" \n') ...
sprintf('.Mue "1.0" \n') ...
sprintf('.Kappa "5.8e+007" \n') ...
sprintf('.Rho "8930.0" \n') ...
sprintf('.ThermalType "Normal" \n') ...
sprintf('.ThermalConductivity "401.0" \n') ...
sprintf('.HeatCapacity "0.39" \n') ...
sprintf('.MetabolicRate "0" \n') ...
sprintf('.BloodFlow "0" \n') ...
sprintf('.VoxelConvection "0" \n') ...
sprintf('.MechanicsType "Isotropic" \n') ...
sprintf('.YoungsModulus "120" \n') ...
sprintf('.PoissonsRatio "0.33" \n') ...
sprintf('.ThermalExpansionRate "17" \n') ...
sprintf('.Colour "1", "1", "0" \n') ...
sprintf('.Wireframe "False" \n') ...
sprintf('.Reflection "False" \n') ...
sprintf('.Allowoutline "True" \n') ...
sprintf('.Transparentoutline "False" \n') ...
sprintf('.Transparency "0" \n') ...
sprintf('.Create\n') ...
sprintf('End With')]);
%---------------------------------------------------------

%------------------ Rogers RT5880 History ----------------
mws.invoke('AddToHistory','Define Roger Material',[...
sprintf('With Material \n') ...
sprintf('     .Reset \n') ...
sprintf('     .Name "Rogers RT5880 (lossy)" \n') ...
sprintf('     .Folder "" \n') ...
sprintf('.FrqType "all"  \n') ...
sprintf('.Type "Normal"  \n') ...
sprintf('.SetMaterialUnit "GHz", "mm" \n') ...
sprintf('.Epsilon "2.2"  \n') ...
sprintf('.Mue "1.0"  \n') ...
sprintf('.Kappa "0.0"  \n') ...
sprintf('.TanD "0.0009"  \n') ...
sprintf('.TanDFreq "10.0"  \n') ...
sprintf('.TanDGiven "True"  \n') ...
sprintf('.TanDModel "ConstTanD"  \n') ...
sprintf('.KappaM "0.0"  \n') ...
sprintf('.TanDM "0.0"  \n') ...
sprintf('.TanDMFreq "0.0"  \n') ...
sprintf('.TanDMGiven "False"  \n') ...
sprintf('.TanDMModel "ConstKappa"  \n') ...
sprintf('.DispModelEps "None"  \n') ...
sprintf('.DispModelMue "None"  \n') ...
sprintf('.DispersiveFittingSchemeEps "General 1st"  \n') ...
sprintf('.DispersiveFittingSchemeMue "General 1st"  \n') ...
sprintf('.UseGeneralDispersionEps "False"  \n') ...
sprintf('.UseGeneralDispersionMue "False"  \n') ...
sprintf('.Rho "0.0"  \n') ...
sprintf('.ThermalType "Normal"  \n') ...
sprintf('.ThermalConductivity "0.20"  \n') ...
sprintf('.SetActiveMaterial "all"  \n') ...
sprintf('.Colour "0.94", "0.82", "0.76"  \n') ...
sprintf('.Wireframe "False"  \n') ...
sprintf('.Transparency "0"  \n') ...
sprintf('.Create \n') ...
sprintf('End With')]);
%---------------------------------------------------------


%---------------------- Foam History ---------------------
mws.invoke('AddToHistory','Define Foam Material',[...
sprintf('With Material \n') ...
sprintf('     .Reset \n') ...
sprintf('     .Name "Foam" \n') ...
sprintf('     .Folder "" \n') ...
sprintf('.FrqType "all"  \n') ...
sprintf('.Type "Normal"  \n') ...
sprintf('.SetMaterialUnit "GHz", "mm" \n') ...
sprintf('.Epsilon "1.37"  \n') ...
sprintf('.Mue "1.0"  \n') ...
sprintf('.Kappa "0.0"  \n') ...
sprintf('.TanD "0.025"  \n') ...
sprintf('.TanDFreq "10.0"  \n') ...
sprintf('.TanDGiven "True"  \n') ...
sprintf('.TanDModel "ConstTanD"  \n') ...
sprintf('.KappaM "0.0"  \n') ...
sprintf('.TanDM "0.0"  \n') ...
sprintf('.TanDMFreq "0.0"  \n') ...
sprintf('.TanDMGiven "False"  \n') ...
sprintf('.TanDMModel "ConstKappa"  \n') ...
sprintf('.DispModelEps "None"  \n') ...
sprintf('.DispModelMue "None"  \n') ...
sprintf('.DispersiveFittingSchemeEps "General 1st"  \n') ...
sprintf('.DispersiveFittingSchemeMue "General 1st"  \n') ...
sprintf('.UseGeneralDispersionEps "False"  \n') ...
sprintf('.UseGeneralDispersionMue "False"  \n') ...
sprintf('.Rho "0.0"  \n') ...
sprintf('.ThermalType "Normal"  \n') ...
sprintf('.ThermalConductivity "0.3"  \n') ...
sprintf('.SetActiveMaterial "all"  \n') ...
sprintf('.Colour "0.94", "0.82", "0.76"  \n') ...
sprintf('.Wireframe "False"  \n') ...
sprintf('.Transparency "0"  \n') ...
sprintf('.Create \n') ...
sprintf('End With')]);
%---------------------------------------------------------

%-------------------- Parameters -------------------------
W_ref=162;
mws.invoke('StoreDoubleParameter','W_ref','162');
mws.invoke('StoreDoubleParameter','w','10');
W_Ka = 10;
mws.invoke('StoreDoubleParameter','W_Ka','10');
mws.invoke('StoreDoubleParameter','h',' 1.16');
 
mws.invoke('StoreDoubleParameter','t',' 0');

mws.invoke('StoreParameter','isol',' 0.8');
mws.invoke('StoreParameter','r_cycl',' 0.8');
%---------------------------------------------------------


%------------------- 1Ground History ---------------------
mws.invoke('AddToHistory','new component:component00','Component.New "component00"');
mws.invoke('AddToHistory','Define Ground',[...
sprintf('With Brick \n') ...
sprintf('     .Reset  \n') ...
sprintf('     .Name "1Ground"  \n') ...
sprintf('     .Component "component00"  \n') ...
sprintf('     .Material "Copper (annealed)"  \n') ...
sprintf('     .Xrange "-W_ref/2", "W_ref/2"  \n') ...
sprintf('     .Yrange "-W_ref/2", "W_ref/2"  \n') ...
sprintf('     .Zrange "0", "t"  \n') ...
sprintf('     .Create \n') ...
sprintf('End With')]);

%---------------------------------------------------------





%------------------- 2Isolation History ---------------------
mws.invoke('AddToHistory','Define 2Isolation',[...
sprintf('With Brick \n') ...
sprintf('     .Reset  \n') ...
sprintf('     .Name "2Isolation"  \n') ...
sprintf('     .Component "component00"  \n') ...
sprintf('     .Material "Foam"  \n') ...
sprintf('     .Xrange "-W_ref/2", "W_ref/2"  \n') ...
sprintf('     .Yrange "-W_ref/2", "W_ref/2"  \n') ...
sprintf('     .Zrange "t", "t+isol"  \n') ...
sprintf('     .Create \n') ...
sprintf('End With')]);

%---------------------------------------------------------
%------------------- 3Substrate History ---------------------
mws.invoke('AddToHistory','Define 2DSubstrate',[...
sprintf('With Brick \n') ...
sprintf('     .Reset  \n') ...
sprintf('     .Name "3Substrate"  \n') ...
sprintf('     .Component "component00"  \n') ...
sprintf('     .Material "Rogers RT5880 (lossy)"  \n') ...
sprintf('     .Xrange "-W_ref/2", "W_ref/2"  \n') ...
sprintf('     .Yrange "-W_ref/2", "W_ref/2"  \n') ...
sprintf('     .Zrange "t+isol", "t+isol+h"  \n') ...
sprintf('     .Create \n') ...
sprintf('End With')]);

%---------------------------------------------------------

Dim_Val = xlsread('dim_value');
%---------------------- 4Circle History---------------------
for i = 1:1:size(Dim_Val)
name=sprintf('Define 4Circle%d',i);        
mws.invoke('AddToHistory',name,[...
sprintf('With Cylinder  \n') ...
sprintf('     .Reset  \n') ...
sprintf('     .Name "4Circle%d"  \n', i) ...
sprintf('     .Component "component01"  \n') ...
sprintf('     .Material "Copper (annealed)"  \n') ...
sprintf('     .OuterRadius "%d*r_cycl"  \n',Dim_Val(i,4)) ...
sprintf('     .InnerRadius "0"  \n') ...
sprintf('     .Axis "z"  \n') ...
sprintf('     .Zrange "t+isol+h", "t+isol+h+t"  \n') ...
sprintf('     .Xcenter "%d"  \n',Dim_Val(i,1)) ...
sprintf('     .Ycenter "%d"  \n',Dim_Val(i,2)) ...
sprintf('     .Segments "0"  \n') ...
sprintf('     .Create \n') ...
sprintf('End With')]);
end
%---------------------------------------------------------

%---------------------- 5Cell History---------------------
for i = 1:1:size(Dim_Val)
name=sprintf('Define 5Cell%d',i);        
mws.invoke('AddToHistory',name,[...
sprintf('With Cylinder  \n') ...
sprintf('     .Reset  \n') ...
sprintf('     .Name "5Cell%d"  \n', i) ...
sprintf('     .Component "component02"  \n') ...
sprintf('     .Material "Copper (annealed)"  \n') ...
sprintf('     .OuterRadius "%d"  \n',Dim_Val(i,3)) ...
sprintf('     .InnerRadius "0"  \n') ...
sprintf('     .Axis "z"  \n') ...
sprintf('     .Zrange "t+isol+h", "t+isol+h+t"  \n') ...
sprintf('     .Xcenter "%d"  \n',Dim_Val(i,1)) ...
sprintf('     .Ycenter "%d"  \n',Dim_Val(i,2)) ...
sprintf('     .Segments "6"  \n') ...
sprintf('     .Create \n') ...
sprintf('End With')]);
title=sprintf('boolean subtract shapes: component02:5Cell%d, component01:4Circle%d" \n',i);
mws.invoke('AddToHistory',title,...
sprintf('Solid.subtract "component02:5Cell%d", "component01:4Circle%d" \n',i,i));
end
%---------------------------------------------------------






mws.invoke('Save');
